PLUGINOBJECTS = \
	Swirl.o \
	Implode.o \
	PluginRegistration.o \

PLUGINNAME = Filter

RESOURCES = \
net.fxarena.openfx.Swirl.png \
net.fxarena.openfx.Swirl.svg \
net.fxarena.openfx.Implode.png \
net.fxarena.openfx.Implode.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
