PLUGINOBJECTS = \
	Swirl.o \
	Implode.o \
        UnsharpMask.o \
	Polar.o \
        Arc.o \
	PluginRegistration.o \

PLUGINNAME = Filter

RESOURCES = \
net.fxarena.openfx.Swirl.png \
net.fxarena.openfx.Swirl.svg \
net.fxarena.openfx.Implode.png \
net.fxarena.openfx.Implode.svg \
net.fxarena.openfx.UnsharpMask.png \
net.fxarena.openfx.UnsharpMask.svg \
net.fxarena.openfx.Polar.png \
net.fxarena.openfx.Polar.svg \
net.fxarena.openfx.Arc.png \
net.fxarena.openfx.Arc.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
