PLUGINOBJECTS = \
	Mirror.o \
	PluginRegistration.o \

PLUGINNAME = Transform

RESOURCES = \
net.fxarena.openfx.Mirror.png \
net.fxarena.openfx.Mirror.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
