PLUGINOBJECTS = \
        Edges.o \
        PluginRegistration.o \

PLUGINNAME = Edges

RESOURCES = \
net.fxarena.openfx.Edges.png \
net.fxarena.openfx.Edges.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
