PLUGINOBJECTS = \
        Sketch.o

PLUGINNAME = Sketch

RESOURCES = \
net.fxarena.openfx.Sketch.png \
net.fxarena.openfx.Sketch.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
