PLUGINOBJECTS = \
        Glow.o \
        PluginRegistration.o \

PLUGINNAME = Glow

RESOURCES = \
net.fxarena.openfx.Glow.png \
net.fxarena.openfx.Glow.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
