PLUGINOBJECTS = \
        TextPango.o

PLUGINNAME = TextPango

RESOURCES = \
net.fxarena.openfx.TextPango.png \
net.fxarena.openfx.TextPango.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS) $(FCONFIG_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS) $(FCONFIG_LINKFLAGS)
