PLUGINOBJECTS = \
        Swirl.o \
	MagickPlugin.o

PLUGINNAME = Swirl

RESOURCES = \
net.fxarena.openfx.Swirl.png \
net.fxarena.openfx.Swirl.svg

SRCDIR = ../..
include $(SRCDIR)/Magick/Makefile.Magick

