PLUGINOBJECTS = \
        Oilpaint.o

PLUGINNAME = Oilpaint

RESOURCES = \
net.fxarena.openfx.Oilpaint.png \
net.fxarena.openfx.Oilpaint.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
