PLUGINOBJECTS = \
        Implode.o \
        PluginRegistration.o \

PLUGINNAME = Implode

RESOURCES = \
net.fxarena.openfx.Implode.png \
net.fxarena.openfx.Implode.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
