PLUGINOBJECTS = \
        Emboss.o \
        PluginRegistration.o \

PLUGINNAME = Emboss

RESOURCES = \
net.fxarena.openfx.Emboss.png \
net.fxarena.openfx.Emboss.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
