PLUGINOBJECTS = \
	GmicGeneric.o \
	gmic.o \
	PluginRegistration.o \

PLUGINNAME = GMIC

VPATH = gmic/src

RESOURCES = \
net.fxarena.openfx.GmicGeneric.png \
net.fxarena.openfx.GmicGeneric.svg \

include ../Makefile.master

CXXFLAGS += $(GMIC_CXXFLAGS)
LINKFLAGS += $(GMIC_LINKFLAGS)

