PLUGINOBJECTS = \
        Modulate.o \
        PluginRegistration.o \

PLUGINNAME = Modulate

RESOURCES = \
net.fxarena.openfx.Modulate.png \
net.fxarena.openfx.Modulate.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
