PLUGINOBJECTS = \
	MagickSwirl.o \
	MagickMirror.o \
	MagickImplode.o \
	MagickTile.o \
	PluginRegistration.o \

PLUGINNAME = Magick

RESOURCES = \
net.fxarena.openfx.MagickSwirl.png \
net.fxarena.openfx.MagickSwirl.svg \
net.fxarena.openfx.MagickMirror.png \
net.fxarena.openfx.MagickMirror.svg \
net.fxarena.openfx.MagickImplode.png \
net.fxarena.openfx.MagickImplode.svg \
net.fxarena.openfx.MagickTile.png \
net.fxarena.openfx.MagickTile.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
