PLUGINOBJECTS = Arc.o

PLUGINNAME = Arc

RESOURCES = \
net.fxarena.openfx.Arc.png \
net.fxarena.openfx.Arc.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
