PLUGINOBJECTS = TextFX.o

PLUGINNAME = TextFX

RESOURCES = \
fr.inria.openfx.TextFX.png \
fr.inria.openfx.TextFX.svg

include ../Makefile.master

CXXFLAGS += $(FCONFIG_CXXFLAGS) $(PANGO_CXXFLAGS)
LINKFLAGS += $(FCONFIG_LINKFLAGS) $(PANGO_LINKFLAGS)
