PLUGINOBJECTS = \
        Polar.o

PLUGINNAME = Polar

RESOURCES = \
net.fxarena.openfx.Polar.png \
net.fxarena.openfx.Polar.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
