PLUGINOBJECTS = \
        Polaroid.o \
        PluginRegistration.o \

PLUGINNAME = Polaroid

RESOURCES = \
net.fxarena.openfx.Polaroid.png \
net.fxarena.openfx.Polaroid.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
