PLUGINNAME = Audio

PLUGINOBJECTS = AudioCurve.o

RESOURCES = net.fxarena.openfx.AudioCurve.png

SRCDIR = ..
include $(SRCDIR)/Makefile.master

CXXFLAGS  += $(SOX_CXXFLAGS)
LINKFLAGS += $(SOX_LINKFLAGS)
