PLUGINOBJECTS = \
        WaveletDenoise.o

PLUGINNAME = WaveletDenoise

RESOURCES = \
fr.inria.openfx.WaveletDenoise.png \
fr.inria.openfx.WaveletDenoise.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
