PLUGINOBJECTS = \
        Tile.o 

PLUGINNAME = Tile

RESOURCES = \
net.fxarena.openfx.Tile.png \
net.fxarena.openfx.Tile.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
