PLUGINOBJECTS = \
        Texture.o \
	PluginRegistration.o \

PLUGINNAME = Texture

RESOURCES = \
net.fxarena.openfx.Texture.png \
net.fxarena.openfx.Texture.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
