PLUGINOBJECTS = \
        Distort.o \
	PluginRegistration.o \

PLUGINNAME = Distort

RESOURCES = \
net.fxarena.openfx.Distort.png \
net.fxarena.openfx.Distort.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
