PLUGINOBJECTS = \
        PovRay.o \
	PluginRegistration.o \

PLUGINNAME = PovRay

RESOURCES = \
net.fxarena.openfx.PovRay.png \
net.fxarena.openfx.PovRay.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
