PLUGINOBJECTS = \
        Swirl.o \
        ofxsOGLTextRenderer.o \
        ofxsOGLFontData.o \
        ofxsRectangleInteract.o

PLUGINNAME = Swirl

RESOURCES = \
net.fxarena.openfx.Swirl.png \
net.fxarena.openfx.Swirl.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
