PLUGINOBJECTS = \
        Roll.o

PLUGINNAME = Roll

RESOURCES = \
net.fxarena.openfx.Roll.png \
net.fxarena.openfx.Roll.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
