PLUGINOBJECTS = \
	Mirror.o \
	Tile.o \
        Reflection.o \
	PluginRegistration.o \

PLUGINNAME = Transform

RESOURCES = \
net.fxarena.openfx.Mirror.png \
net.fxarena.openfx.Mirror.svg \
net.fxarena.openfx.Tile.png \
net.fxarena.openfx.Tile.svg \
net.fxarena.openfx.Reflection.png \
net.fxarena.openfx.Reflection.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
