PLUGINOBJECTS = \
    ReadMisc.o \
    GenericReader.o GenericOCIO.o SequenceParsing.o

PLUGINNAME = ReadMisc

RESOURCES = fr.inria.openfx.ReadMisc.png fr.inria.openfx.ReadMisc.svg

include ../Makefile.master
include ../Makefile.io

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
