PLUGINOBJECTS = \
        Charcoal.o \
        PluginRegistration.o \

PLUGINNAME = Charcoal

RESOURCES = \
net.fxarena.openfx.Charcoal.png \
net.fxarena.openfx.Charcoal.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
