PLUGINOBJECTS = \
        Reflection.o

PLUGINNAME = Reflection

RESOURCES = \
net.fxarena.openfx.Reflection.png \
net.fxarena.openfx.Reflection.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
