PLUGINOBJECTS = Wave.o

PLUGINNAME = Wave

RESOURCES = \
net.fxarena.openfx.Wave.png \
net.fxarena.openfx.Wave.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
