PLUGINNAME = AudioCurve

PLUGINOBJECTS = AudioCurveOFX.o

RESOURCES = net.fxarena.openfx.AudioCurve.png

SRCDIR = ..
include $(SRCDIR)/Makefile.master

CXXFLAGS  += -std=c++11
CXXFLAGS  += $(SOX_CXXFLAGS)
LINKFLAGS += $(SOX_LINKFLAGS)
