name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-20.04
    name: Ubuntu 20.04 GCC 9
    steps:
    - uses: actions/checkout@v2
    - name: apt install
      run: sudo apt-get install libopencolorio-dev libgl-dev libfftw3-dev libmagick++-dev liblcms2-dev libfontconfig1-dev libpango1.0-dev libxml2-dev libzip-dev librsvg2-dev libglib2.0-dev libcairo-dev libpoppler-dev libpoppler-glib-dev libpoppler-private-dev librevenge-dev libcdr-dev libsox-dev libcurl4-openssl-dev
    - name: submodules
      run: git submodule update -i --recursive
    - name: build (release)
      run: make -j2 CONFIG=release
    - name: build (debug)
      run: make -j2 CONFIG=debug

  msys:
    runs-on: windows-2019
    defaults:
      run:
        shell: bash.exe --login -eo pipefail "{0}"
    env:
      MSYSTEM: "MINGW64"
      CHERE_INVOKING: 1
    name: Windows 10 Custom MSYS2 GCC 7
    steps:
      - name: Install Natron MSYS2
        run: |
          echo insecure > ~/.curlrc
          curl -k -L http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20180531.tar.xz -o msys64.tar.xz
          tar xf msys64.tar.xz
          mv msys64 /c/msys64-20180531
      - name: Setup Natron MSYS2
        run: echo "C:\msys64-20180531\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh
      - name: Run Natron MSYS2
        run: echo "C:\msys64-20180531\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh
      - name: pacman
        run: |
          uname -a
          export PATH="/c/msys64-20180531/usr/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
          export PKG_CONFIG_PATH="/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig"
          sed -i 's/SigLevel    = Required DatabaseOptional/SigLevel = Never/' /etc/pacman.conf
          sed -i 's|#XferCommand = /usr/bin/curl -L -C - -f -o %o %u|XferCommand = /usr/bin/curl -k -L -C - -f -o %o %u|' /etc/pacman.conf
          echo "Server = https://downloads.sourceforge.net/project/natron/MINGW-packages/mingw64" > /etc/pacman.d/mirrorlist.mingw64
          echo "Server = https://downloads.sourceforge.net/project/natron/MINGW-packages/msys" > /etc/pacman.d/mirrorlist.msys
          echo insecure > ~/.curlrc
          pacman --version
          pacman -Syu --noconfirm tree gettext openfx-arena-sdk || pacman -Syu --noconfirm tree gettext openfx-arena-sdk || pacman -Syu --noconfirm tree gettext openfx-arena-sdk
      - name: Build (release)
        run: |
          env
          gcc -v
          pwd
          mv /mingw64/bin/envsubst.exe /mingw64/bin/envsubst.exe.orig
          git clone https://github.com/NatronGitHub/openfx-arena
          cd openfx-arena
          git checkout $GITHUB_SHA
          git submodule update -i --recursive
          make -j2 CONFIG=release
