name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: apt install
      run: sudo apt-get install libopencolorio-dev libgl-dev libfftw3-dev libmagick++-dev liblcms2-dev libfontconfig1-dev libpango1.0-dev libxml2-dev libzip-dev librsvg2-dev libglib2.0-dev libcairo-dev libpoppler-dev libpoppler-glib-dev libpoppler-private-dev librevenge-dev libcdr-dev libsox-dev libcurl4-openssl-dev
    - name: submodules
      run: git submodule update -i --recursive
    - name: build (release)
      run: make CONFIG=release
    - name: build (debug)
      run: make CONFIG=debug

  msys:
    runs-on: windows-2019
    defaults:
      run:
        shell: bash.exe --login -eo pipefail "{0}"
    env:
      MSYSTEM: "MINGW64"
      CHERE_INVOKING: 1
    name: MSYS2
    steps:
      - name: Set up msys
        run: |
          wget http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20180531.tar.xz
          mv msys64 /c/msys64-20180531
      - name: Set up shell
        run: echo "C:\msys64-20180531\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh
      - name: pacman
        run: |
          uname -a
          export PATH="/c/msys64-20180531/usr/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
          ls /usr/bin
          /usr/bin/pacman --version
