PLUGINOBJECTS = \
	Text.o \
	ofxsOGLTextRenderer.o \
	ofxsOGLFontData.o \
	ofxsRectangleInteract.o \
	PluginRegistration.o \

PLUGINNAME = Image

RESOURCES = \
net.fxarena.openfx.Text.png \
net.fxarena.openfx.Text.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
